/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_gad_jni_SayHello */

#ifndef _Included_de_gad_jni_SayHello
#define _Included_de_gad_jni_SayHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_gad_jni_SayHello
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_gad_jni_SayHello_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
